version: 2

jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install rust stable 
          command: rustup install stable 
      - run:
          name: Install rust nightly 
          command: rustup install nightly 
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Build Nightly
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Build Stable
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build 
      - run:
          name: Run Tests
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
